### ISSUE TITLE
describe our API endpoint

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#102]
It's an obvious interoperability/documentation issue when we want to make the SIS available to outside services.
The issue came up at the most recent CSC meeting -- thanks to Daan for bringing it up.

**Comment by margaretha** [comment]
REST-Style Web API: https://exist-db.org/exist/apps/doc/devguide_rest

**Comment by margaretha** [comment]
I have investigated the REST API and enabled it for the production. 
Next, I will write a short description and add it to the web.
Piotr will update the description later.

**Comment by bansp** [comment]
We'll wait until the next upload to production with this. 
Target audience: among others, centres which prefer to publish this information locally rather that point at SIS.

**Comment by margaretha** [comment]
I have wrote some descriptions about the API in 66109debbfcaf070874aa7fcb367bf03590b2236
and it can be accessed on the website at
https://clarin.ids-mannheim.de/standards/views/api.xq
