### ISSUE TITLE
Suggestion regarding the description of format ID="fMPEG-4-AVC", commitId=dbd479c

### ISSUE THREAD

**Issue by berndmoos** [clarin-eric/standards#103]
**Change / add the format description**
There's been a historical typo in the format specification which has also landed here: resolution should be **1920**x1080, not _1980_x1080.

**Comment by bansp** [comment]
Thanks, Thomas -- fixed in the source. I'll leave the issue open until the change makes it to the online instance, which is going to take a while now, because of the vacation season.

**Comment by bansp** [comment]
Closing this for the 2.1.0 source release, which will go online soon(ish).
