### ISSUE TITLE
Suggestion regarding the description of format ID="fDCXML", commitId=c500d4b

### ISSUE THREAD

**Issue by hannahedeland** [clarin-eric/standards#109]
This is not among the formats in https://github.com/clarin-eric/standards/tree/master/SIS/clarin/data/formats - it is now https://github.com/clarin-eric/standards/blob/master/SIS/clarin/data/formats/fDC-XML.xml - but still listed on https://clarin.ids-mannheim.de/standards/views/list-formats.xq among the formats without references?

**Comment by bansp** [comment]
Hi Hanna,
It _is_ among the https://github.com/clarin-eric/standards/tree/master/SIS/clarin/data/formats formats. It's just not referenced by any centre. I think all is correct.

**Comment by bansp** [comment]
Ah, but I can see what you mean, I think: the ID without the hyphen, right?
OK, so that would mean that it should get deleted from the production instance.
Super, thanks for the catch! :-)

**Comment by margaretha** [comment]
Thanks for the feedback. Sorry I made a mess with the commits but it is fixed now.
