### ISSUE TITLE
Replace <date> with <lastUpdateCommitID> in the recommendation schema

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#116]
Following issue #81, the recommendation scheme should support `<lastUpdateCommitID>` instead of `<date>`.

The `<date>` elements in the [recommendation files](https://github.com/clarin-eric/standards/tree/master/SIS/clarin/data/recommendations) should also be updated with `<lastUpdateCommitID>`.

**Comment by margaretha** [comment]
@bansp There is `<lastUpdate> ` element within the recommendation header. It is probably not needed anymore, is it?
https://github.com/clarin-eric/standards/blob/e99e5b6938f82b8aa0c8e9e18c4bd3b1217ea60b/SIS/clarin/schemas/recommendation.xsd#L30

**Comment by bansp** [comment]
No, thanks for asking. As we talked, the commit ID will also carry its date information, and we simply need info on the point in the development at which the export happened. So please eliminate that lastUpdate element.

**Comment by margaretha** [comment]
Done in 7e23a85389fa8fd733e520c741fa7f47769f17e4

**Comment by bansp** [comment]
All done, closing. Thanks, Eliza! :-)
