### ISSUE TITLE
Provide a link from the metadomain to a filtered list of all the domains in that metadomain

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#125]
This ticket is an offshoot of ticket #120 .

At page https://clarin.ids-mannheim.de/standards/views/list-domains.xq , the domain names are going to link to lists filtered by the given domain (that's what the **original ticket** is going to handle). So, from "Audiovisual Annotation", we are going to get to https://clarin.ids-mannheim.de/standards/views/recommended-formats-with-search.xq?domain=6

**This ticket** is for the 'metadomains' such as "Annotation" -- let's make them clickable as well, and let's make them take the user to lists filtered by several domains. So, clicking on "Annotation" would take us to a list containing recommendations for three domains: Audiovisual Annotation, Image Annotation, and Text Annotation.

An additional thing to make sure of is to have all three of them in the XML export, so the `filter` element in the export is going to be
```xml
<filter>
<domain>Audiovisual Annotation</domain>
<domain>Image Annotation</domain>
<domain>Text Annotation</domain>
</filter>
```

**Comment by bansp** [comment]
Definitely, let's experiment and see what works. And later on, we can try to restructure the information, if needed.

**Comment by bansp** [comment]
It seems to me that the primary focus should be moved here, or maybe made the topic of a separate ticket, with this one still being tagged as an enhancement. The actual primary task seems to be to be the ability to sort on more than one condition of the same kind: multiple domains, but also multiple formats, if someone searches for all STATA formats and wants to see how they are supported in some domains (including e.g. "Other"). Or someone clicking on a node in a format family tree, to see how the children of that node are supported. Or multiple domains, as in this very ticket.

![image](https://user-images.githubusercontent.com/312137/170723816-3d57cc8f-d57f-46c9-8f94-f17c03ac850c.png)

(notice, incidentally, that something is off in this list, but that's an issue for a separate issue...)

One way or another, this issue needs to be postponed. Till September for now (task: split it into two tickets), and most probably till even later. So I'll change the milestone.

**Comment by bansp** [comment]
Postponing to ~2023.

**Comment by bansp** [comment]
This may be an important first step for many centres: they will identify the domain coarsely, simply to get the format recommendations in.
It doesn't make sense to prioritise this at this point, but I will assign it to Eliza, to make it easier to keep track of it.

**Comment by margaretha** [comment]
> The actual primary task seems to be to be the ability to sort on more than one condition of the same kind: multiple domains, but also multiple formats

It seems that there is a certain grouping/categorization of the multiple formats or domains. Domains for example are grouped by meta-domain. How should multiple formats are grouped?

Like in the STATA example, should the formats be grouped by such criteria: "all formats with id starting with fSTATA"?

Or will the groups of similar/related formats be defined like the domains in meta-domain?

Or would we like to filter the recommendations by randomly select multiple formats/domains?

@bansp could you please clarify the task?

**Comment by bansp** [comment]
Let's have a separate issue on how formats are grouped (there's several ways, and the semi-structured ones are by keywords and by the format family tree). That was just an example to show that the issue is wider than domains.

And the issue is to be able to find results for multiple values of the same column (domain, format, centre(!)). Oh gosh, centre. Yes, this issue _is_ fundamental.

Leaving the rest to our upcoming meeting and let's add to this ticket afterwards.

**Comment by bansp** [comment]
Eliza will see about filtering for multiple values for domains for now, and we can generalize from that afterwards.

**Comment by margaretha** [comment]
Multi-select mechanism (for domains) has been impemented in 2c528eac23e6992f5792a5bcb1ded642e3b3c5fa.

We still need to enable export with multiple domain filters.

**Comment by bansp** [comment]
Can't wait to test that, thanks, Eliza :-)
And you're right, we mustn't forget about export. Maybe let's have a separate issue for that, or is that going to be automatic?

**Comment by bansp** [comment]
I've posted a new issue #192 about some minor cosmetics.

**Comment by margaretha** [comment]
Thanks for the extended issue, @bansp. This issue has become bigger and bigger :-) We should have made a separate issue for the multi-select and export functions, since this issue depends on them. 

> Can't wait to test that, thanks, Eliza :-) And you're right, we mustn't forget about export. Maybe let's have a separate issue for that, or is that going to be automatic?

Maybe it is not bad to have a separate issue for the export. The multi-select drop-down function has been available in d8033747c0fae8b155017c712d45b0144dbbe401, and the meta-domain links in the "Functional Domains" page have also been available in  07561759767d5fea18964e81098718f369a28ed8, but the table with multiple filter cannot be exported yet. It will produce almost an empty XMLdata. 

What do you mean with automatic?

**Comment by bansp** [comment]
By "automatic" I meant I was wondering if it would be straightforward to move from querying multiple domains at once (via a metadomain) to exporting that same set of values. But since you're indicating that the two should be separated, I will post another ticket.

We should come back to the search issue though, let's try to keep in mind please for our next meeting. Ah, issue #192 is going to help us remember :-)

**Comment by bansp** [comment]
Closing, waiting for the update of the production (soon).
