### ISSUE TITLE
replace the standards cloud with the format keywords cloud

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#133]
This is worth at least trying out, and it might move us one step further with regard to issue #129 .

Replace the current cloud based on standards with one based on format keywords (and we can think later about e.g. mixing the two inputs, but for now, we're focused on formats, and standards are nearly as they were).

**Comment by bansp** [comment]
Decisions made at a meeting:
- relocate the standards cloud to the standards tab, at least temporarily
- put the format keyword cloud onto the home page (replacing the standards cloud)

**Comment by bansp** [comment]
The question is: what do we expect as the action taken when someone clicks on an element of a cloud (a keyword)?

**Comment by bansp** [comment]
Brainstorming at the meeting:

- open a new issue for adding a filter-by-keyword option to the list of formats
- perhaps only keep that new list of formats on the Data Deposition Formats tab
- maybe use a table for the format listing
- relocate the first two items (absent formats and formats not used by recommendations) to the sanity checker page?

**Comment by margaretha** [comment]
> The question is: what do we expect as the action taken when someone clicks on an element of a cloud (a keyword)?

I will add a link for the keyword to the Data Deposition Format page with the keyword as a parameter to automatically filter the list by the keyword.

**Comment by bansp** [comment]
Meeting decision: make Piotr rewrite that description at last!!

**Comment by bansp** [comment]
Done in ee8c4095b2a4176ab97fea04cbe18bcc0feba3ea and submited as #148 .
