### ISSUE TITLE
Add schema location to the exported recommendation data

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#134]
The export functions as found in:
* the [format recommendation page](https://clarin.ids-mannheim.de/standards/views/recommended-formats-with-search.xq)
* a centre page, for instance for [ACDH-ARCHE](https://clarin.ids-mannheim.de/standards/views/view-centre.xq?id=ACDH-ARCHE)

produce a recommendation file without any reference to the recommendation scheme. It is better to include the scheme to enable XML validation.

**Comment by bansp** [comment]
Brainstorming at a meeting:

- in pages for centres without recommendations, we may need a special link to github (which may be problematic from the maintenance point of view) or a special link to export a template (we prefer that one)
- in those pages, we could also keep the same link to a github issue that is displayed in the pages that have content (tables of recommendations)

**Comment by bansp** [comment]
Question: where should the link to the schema point?

- https://clarin.ids-mannheim.de/standards/schemas/recommendation.xsd

**Comment by bansp** [comment]
All done and working.
