### ISSUE TITLE
Export empty recommendation template

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#135]
Some centres haven't provide any recommendations yet, so there is no table of recommendations in their page, for instance [ASV](https://clarin.ids-mannheim.de/standards/views/view-centre.xq?id=ASV). 

As discussed in https://github.com/clarin-eric/standards/issues/42, we have provided some template as a start, for instance:

```
<recommendation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/recommendation.xsd">
    <header>
        <lastUpdateCommitID>bec52cd36a2996677ce07153a19ce774097f9130</lastUpdateCommitID>
        <filter>
         <centre>ASV</centre>
      </filter>
    </header>
    <formats>
    <!--
        <format id="null">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>
    -->
    </formats>
</recommendation>
```
We should provide a link to export this template at the centre page.

**Comment by bansp** [comment]
Brainstorming at a meeting:

- in pages for centres without recommendations, we may need a special link to github (which may be problematic from the maintenance point of view) or a special link to export a template (we prefer that one)
- in those pages, we could also keep the same link to a github issue that is displayed in the pages that have content (tables of recommendations)

**Comment by bansp** [comment]
Done, closing. Thanks, Eliza! :-)
