### ISSUE TITLE
Filter formats by keyword

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#137]
Keywords shown in the format page are shared among multiple formats. They can be used to group similar/related formats.

We may want to add a form in the [format list page](https://clarin.ids-mannheim.de/standards/views/list-formats.xq) to filter the list by keywords.

**Comment by bansp** [comment]
Great idea! :-) Let me just reference the hub issue #129 , so that we can keep track of this.
I wonder if a drop-box will be enough to handle the keywords, but let's just see that in action and potentially improve on that basis.

**Comment by bansp** [comment]
Handled by Eliza in commit 7394b1657107adbd5b7717a84713e7bf8f949c20
