### ISSUE TITLE
add the option of sorting in the ascending/descending order to columns

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#141]
In some cases, it will not be very useful, but in some others, e.g. in the long list of format recommendations, it should be very helpful to be able to reverse the sort.

**Comment by margaretha** [comment]
After a second thought, I think it is may not be very helpful since only ZIP, XSLT and XML would be shown using reverse sort. 

Maybe it is better to filter by alphabets ?

**Comment by bansp** [comment]
and/or to filter some stuff out... let's talk about that tomorrow

**Comment by bansp** [comment]
I think your suggestion regarding narrowing the results by alphabet may be close to ideal.

**Comment by bansp** [comment]
This is going to be fixed by #132
