### ISSUE TITLE
Popular formats

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#143]
Eliza has prepared a list-statistics.xq page where a beginning can be seen, ordered by domains and then by the numbers of recommendations in those domains.
We're going to have a settable threshold; what gets displayed is formats with the number of recommendations equal to the threshold and above.
And there will be another setting (it's an experiment!) for showing either all the formats that make the threshold or just the top three **values** of occurrences. (By that we mean that if formats are tied for the number of recommendations, we get to see all the formats that have the given value).

_Originally posted by @bansp in https://github.com/clarin-eric/standards/issues/67#issuecomment-1074972680_

**Comment by margaretha** [comment]
I decided to make a new issue for this because the task is actually not so trivial. 

I also made some decisions in the implementation:
- I created a new page for this because the list is quite long.
- by default all recommendations are listed and firstly sorted alphabetically by domain name and then descendingly by the number of recommendations  

These have been implemented in f328cbd1dea6965600511dccb447a83d0ec6febf which also includes a filter by number of recommendations as the threshold.

The other filter approach showing only formats with 3 highest recommendations  is added in 28eba1bc65b8ab842f14d315d4c8aa3ad5f5246e.

**Comment by bansp** [comment]
Eliza... the page looks totally, totally smashing! It even offers some guidance as to which format description to target next.
Thanks a lot, great job! :-)

**Comment by bansp** [comment]
Do you see a chance of this page going live before Monday the 28th noon? The CSC is meeting then and I would love to be able to show it to the members, I think they would be happy to see this.

Ah, one thought I had is that the list could benefit from some shading of every second domain, so that the results for each next domain would be visually distinct from those for the previous one. But it's the kind of beautification that can wait, so I'm just sharing the idea for now.

**Comment by margaretha** [comment]
Thanks for your kind feedback, Piotr!
I have updated the production with these changes including the shading.

**Comment by bansp** [comment]
Many thanks for that, again. It was nice to be able to present this to the CSC members, because it recreates (in a much better way) something that we had back in the times of the "KPI spreadsheet".

I think the issue is ready to be closed.
