### ISSUE TITLE
Suggestion regarding the description of format ID="fFoLiA"

### ISSUE THREAD

**Issue by proycon** [clarin-eric/standards#145]
> This template is linked from several places in the SIS. Please feel encouraged to delete the fields below that are irrelevant to your report (including this lead text).

**Format short name / ID** FoLiA

> Formats that have descriptions in the SIS  are best identified by their internal IDs, otherwise please use a name that identifies the format well (we will supply the ID). Feel welcome to remove this section if the ID is auto-referenced in the title of this issue.

**Add / correct the following fields**
- Long name: *FoLiA: Format for Linguistic Annotation*
- Keywords: text, linguistic annotation, NLP, speech transcription, text structure, text markup, document-based, xml, morpho-syntactic annotation
- File extension: ``xml``, ``folia.xml``
- Media type: application/folia+xml, text/folia+xml, application/xml
- Format family: XML
- Domain: Text Annotation, Textual Source Language Data
- Standard that defines or uses the format: https://folia.readthedocs.io/en/latest/index.html

**Change / add the format description**

FoLiA, an acronym for Format for Linguistic Annotation, is a data model and file format to represent digitised language resources enriched with linguistic annotation, e.g. linguistically enriched textual documents or transcriptions of speech. The format is intended to provide a standard for the storage and exchange of such language resources, including corpora and to promote interoperability between Natural Language Processing tools that use the format.

**Notes**:

I added 'Text Annotation' to the domain, FoLiA is comparable to initiatives like TCF, PAULA, Tiger that are also in there..

**Comment by bansp** [comment]
Thanks a lot, Maarten! This is now in the source and will be uploaded to the live instance with the current batch of modifications.
I went thrifty on the keywords for now (but made a note of the suggestions in the source), because we still need some little task force to work on what we want/need to have there.

As for the media types, I understand that `application/folia+xml`, `text/folia+xml` are suggested but not registered. This may inspire a new issue for us, so thanks again.

**Comment by bansp** [comment]
It's online now, and #146 is a new issue inspired by this ticket; thanks again!

**Comment by proycon** [comment]
Thanks!
