### ISSUE TITLE
the merge hook needs a clear instruction

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#164]
I have pushed some changes live, for the next release. and I did it github-internally, by creating a PR from 'formats' and merging it, because I thought this would trigger the hook, but should I rather have merged into the master manually, rather than by PR?

We need to clarify this, for a checklist on updating the SIS.

**Comment by bansp** [comment]
The hook triggers when you pull and merge locally, Eliza says.

**Comment by margaretha** [comment]
We use [post-merge](https://git-scm.com/docs/githooks#_post_merge) which is invoked when pulling with merge, not rebase e.g. from a dev branch to a local repository. The commit.xml file will be re-written with the latest commit-id from the history. The local repository can then  be pushed into master including the updated commit-id.xml.

**Comment by bansp** [comment]
Adding to the upcoming milestone, so that we don't lose sight of this issue when reviewing.

**Comment by bansp** [comment]
This is a link for some basic documentation:

https://github.com/clarin-eric/standards/wiki/The-merge-hook

**Comment by margaretha** [comment]
I have written a short description about the merge hook. Please take a look and let me know if it is not clear enough.
