### ISSUE TITLE
clearly display info on whether a centre's recommendations have been curated / confirmed by that centre

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#169]
~~We can actually implement the second certification clause this way ("say what is to be done with formats, for which there is no explicit recommendations"), and it is simply needed for properly interpreting some recommendations.~~

There should be a container in this info that provides contact addresses to "centre representatives", or at least mentions their GitHub handles. If this slot if filled, we will consider the info ready-for-public-consumption, otherwise we should display a **warning**.

(Struck out stuff that has become irrelevant for this very ticket.)

**Comment by bansp** [comment]
Ah, in particular, the warning for DANS should still be displayed, because all their info has been done by us (or by me alone, I forget), with _our_ interpretations. So making such a warning go away should not be fully automated. Or there should be a way to override such an automatic switch.

**Comment by bansp** [comment]
This issue has drifted from its original subject line, which referenced something that had already been implemented and then forgotten. What has come to the fore is the very real issue of us providing clear, explicit information on whether the centre's info has been extracted by us, populating the SIS for testing, or whether it has been confirmed / curated by the centre itself (and then, when and possibly by whom). 
So I'll change the subject now.

**Comment by bansp** [comment]
I think we need to get this handled before inputhons can begin.

**Comment by bansp** [comment]
We have this information in the system already, at least partially.
We need to display it. Among others, we need the name of the person responsible and ideally, their github handle, and the date.

**Comment by bansp** [comment]
We're going to have the following piece of XML for curated centres:
```xml
      <respStmt>
         <name></name>
         <github></github>
         <date></date>
      </respStmt>
```

If the name and the date fields are filled, a message is going to be displayed on the centre page stating that the information has been curated by (name) on (date).

Question: when do we modify the respStmt?

**Comment by bansp** [comment]
- it's better to say `<reviewDate>` and `<curator>`
- it should be a placeholder
- the whole thing is optional, but if it appears, the curator and reviewDate fields are mandatory

**Comment by bansp** [comment]
I have addressed the schema-related part of this issue in #195 . So this ticket is left for implementation by @margaretha and I will unassign it from myself.

**Comment by margaretha** [comment]
We need to agree on the date format.

**Comment by bansp** [comment]
I used `xs:date`, so yyyy-mm-dd. I should probably add an annotation to the datatype.

**Comment by bansp** [comment]
Looks great to me!

**Comment by bansp** [comment]
So, just to record this, this is what we see when I activate the placeholder:

![image](https://user-images.githubusercontent.com/312137/237062482-7f8ddb16-ff43-40a1-b31a-e03dfbb6dd20.png)

In theory, a single centre might get curated by two different persons if it represents two different RIs, but I think we should leave that as is, and leave it to the given institution to settle.
In other words, from my perspective, it's a go :-)
