### ISSUE TITLE
Make Clarin centres linkable in format recommendations

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#185]
The [format recommendation](https://clarin.ids-mannheim.de/standards/views/recommended-formats-with-search.xq) table has a Clarin centre column. As centres now have description pages, it would be handy to have them link to their pages.

**Comment by bansp** [comment]
Absolutely. Thanks, Eliza! :-)

**Comment by bansp** [comment]
Ah, it's actually a duplicate of #153 -- and that rather conveniently places the fix in Eliza's hands, what's not to like about that! :-)

**Comment by bansp** [comment]
Closing as duplicate, assigned Eliza to the other one.
