### ISSUE TITLE
i18n of the data fields

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#203]
For Text+, at least some data fields (such as the centre description, but also recommendation descriptions, so both `<info>` and `<comment>`) should be available in more than one language.

This may need to be a hub ticket, with individual tickets for at least

- schemas (#207 ), 
- functionality (lg switch and maintaining it, #218 ), 
- API (#208 )

Putting this, initially, into 2.6.0, although that milestone is already slowly getting filled. But let's try.

**Comment by margaretha** [comment]
The functionality for language or RI switch is described in  https://github.com/clarin-eric/standards/issues/218

**Comment by bansp** [comment]
Done :-)
