### ISSUE TITLE
Make sure the API honours requests for a specific language, or make sure to return fields with an xml:lang label

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#208]
This is with reference to the hub ticket for i18n, #203 .
The IDS recommendations file can be used as an example, for now.
The relevant fields are `<info>` and `<comment>`.

Tentatively aiming for 2.6.0, but...

**Comment by margaretha** [comment]
The REST API has been updated. Now the recommendation files also includes _info_ elements with _xml:lang_.
https://clarin.ids-mannheim.de/standards/rest/data/recommendations/IDS-recommendation.xml

**Comment by bansp** [comment]
Looks great :-)
Let's also have some xml-langed comments (as we talked the last time). I'll see if they need to be added, for testing.

**Comment by bansp** [comment]
Closing, done.
