### ISSUE TITLE
Search recommendation doesn't show results for centres

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#210]
The search recommendation in the [format recommendation page](https://clarin.ids-mannheim.de/standards/views/recommended-formats-with-search.xq?searchFormat=IDS&searchButton=Search#searchRecommendation) doesn't show any results when filtering by a centre, e.g. IDS.

**Comment by bansp** [comment]
Ooopsie, thanks for the catch. Gosh! :-)
I'd rather not release with that bug, so I'd rather go 2.5.0.

**Comment by bansp** [comment]
There is more to this. 

- filter by domain, choose Audiovisual Source, then click on "Filter"
- export to XML, and note that no centres are exported
           
    ![image](https://user-images.githubusercontent.com/312137/229912632-44a528fd-9cf0-463a-8ad9-cfc4ac35bc8b.png)

- type "C" into the search window, choose a centre, so CMU or CLARIN.SI, search
- the result is empty
- at the same time, the domain vanishes from the filter
- export again, and:

     ![image](https://user-images.githubusercontent.com/312137/229913142-cd4ffc93-848a-40e4-a059-18efb34eff09.png)

**Comment by margaretha** [comment]
I have fixed the bugs of missing centres.

> at the same time, the domain vanishes from the filter

When the issue was reported, the feature of combining filter and search functions has not been added yet. It was asked in #192. I have partly implemented it in https://github.com/clarin-eric/standards/commit/95cd5e143b1b325b5fce3f481c2a888e66716a6c but it needs further discussions.

**Comment by margaretha** [comment]
I have wrote the stuff for discussions in #192, so this issue can be closed.
