### ISSUE TITLE
add some github pages that showcase how the info provided by centres can be retrieved via the API and styled locally

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#213]
as in the title.

The task requires an update of one's knowledge about github pages. Mine is very old and obsolete (from 2017 or so).

The idea is to show that a page can retrieve data from the SIS and display them locally. That page can then be used by centres during inputhons.

**Comment by bansp** [comment]
Assigning to Eliza as agreed at our meeting.

**Comment by margaretha** [comment]
Implemented in https://github.com/IDS-Mannheim/IDS-Mannheim.github.io and the webpage is available at https://ids-mannheim.github.io/standards/
