### ISSUE TITLE
Upgrade to eXist 6.3.0

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#214]
This ticket is connected to issue #200 .
eXist 6.2.1 should be out soon, and since it figures for people who would install SIS locally for inputhon-related activities, let's please 

- upgrade our local installations to 6.2.1 and test a bit (meaning: just do regular development)
- handle #200 (that's me)
- handle #332 (offshoot of the above) 
- upgrade the production version (Eliza)

Here is where we can check if 6.2.1 is out: https://github.com/eXist-db/exist/releases

**Comment by bansp** [comment]
6.2.3 is out. So let me change the title of this one and we'll see if we can fit it into the release.

**Comment by margaretha** [comment]
It is actually eXist version 6.3.0. I have installed it locally. There is unfortunately still a problem with the configuration. Changing port via the web-UI doesn't work. 

I did as follows:
1. Run the eXist server by clicking the shortcut as described in our installation procedure. EXist-db configuration would show up. 
2. Change the HTTP Port to 8889 and click save
3. Exist is run at port 8080

4. Right click on the eXist tool  > click system configuration 

![image](https://github.com/user-attachments/assets/0f0cc5e4-9e45-46e7-b8ec-c471f4187407)

5. HTTP Port is still 8080. Changing this to 8889 will break the system as eXists failed to save it to its config file, thus the server cannot start anymore. 

![image](https://github.com/user-attachments/assets/1ecf65c9-9dfb-4b65-b9cc-3f01d6a272d2)

After going to this procedure, _jetty-http.xml_ and _jetty-ssl.xml_ at _/etc/jetty/_ become empty.

A workaround would be to simply use port 8080 or change the port directly at _/etc/jetty/jetty-http.xml_.

It seems that the eXist developers are not aware about this problem. Have we ever inform them about it?

**Comment by bansp** [comment]
Beautiful... Maybe we should really proceed with "the other thing".

As far as

> It seems that the eXist developers are not aware about this problem. Have we ever inform them about it?

- https://github.com/eXist-db/exist/issues/4729
- https://github.com/eXist-db/exist/issues/4916

:-\

**Comment by bansp** [comment]
My goodness, I find it quite telling that the link for the release notes, https://exist-db.org/exist/apps/wiki/blogs/eXist/eXistdb630 (as provided in the [release page](https://github.com/eXist-db/exist/releases/tag/eXist-6.3.0)) , is empty.

**Comment by bansp** [comment]
I have posted comments in both the tickets mentioned above, having tried installing 6.3. 
It requires exactly the same workaround as 6.2.0 (kill, recreate the jetty-html.xml from the backup, modify the value by hand, run).
No further comments...

**Comment by margaretha** [comment]
The production instance has been updated with eXist 6.3.0.
