### ISSUE TITLE
Session cookie for research infrastructure and language switch 

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#218]
We would like to support user-friendly environment for other research infrastructures such as Text+ and Dariah by showing data according to their preferences, e.g. display info in German Text+ if it is available and filter the centre list in the centre page by the RI. The idea is to use a session mechanism to turn on or turn off an RI environment.

**Comment by bansp** [comment]
This issue has been solved very successfully, and remaining details are going to be a matter of new tickets.
