### ISSUE TITLE
Including active RI in exported files 

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#221]
Export function should list only format recommendations according to the active RI (see #220) and include the RI information e.g. within

```
<header>
  <filter>
     <ri>Text+</ri>
  </filter>
</header>

```

**Comment by bansp** [comment]
The state of the list of recommendations should be reflected in the export. And you're right that we should preserve the intension, so to say, as opposed to an unmarked list (extension), where the fact that all the centres belong to a certain RI could, or could not, be the result of specific instructions.

**Comment by margaretha** [comment]
It is actually not a good idea for the exported files to be filtered by RI since they are potentially used by centre representatives to update their recommendation files and by filtering by RI some information will be missing, e.g. info and comment will only be shown for one language.

**Comment by margaretha** [comment]
I have made changes so that info and comments are now included in the exported file from the centre page.

After a second thought, we possibly still need the filter for the exported file in the format recommendation page.

**Comment by bansp** [comment]
I have been thinking this might be a wontfix, but @margaretha 's last remark made me want to discuss this again, to make sure.
Let me prioritise it just to make it stand out a bit.

**Comment by bansp** [comment]
Meeting decision: Piotr will modify the schema to accommodate a `<ri>` under `<filter>`.
