### ISSUE TITLE
Centre options should be filtered by the active RI in the format recommendation page

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#226]
![grafik](https://github.com/clarin-eric/standards/assets/5528620/c4380d0c-ca3e-4d15-96d1-41a698ea6d2c)

As shown in the screenshot above, all centers are listed regardless of the selected RI environment. We can improve this by limiting the options to include only centers of the selected RI.

**Comment by bansp** [comment]
We need more content here, @margaretha -- which options do you mean, please?

**Comment by margaretha** [comment]
I have added some description.
