### ISSUE TITLE
Centre recommendations should be downloaded from centre pages

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#233]
The following snippet from the wikipage [Updating format recommendations](https://github.com/clarin-eric/standards/wiki/Updating-format-recommendations) should be updated. Due to filtering by RI-environment, centre recommendations should be downloaded from centre pages.

> In order to check what the recommendations are, go to https://standards.clarin.eu/sis/views/recommended-formats-with-search.xq , find your centre in the "Select centre" box, and hit "search". Another handy option is to start at https://clarin.ids-mannheim.de/standards/views/list-centres.xq and select your centre from there.

**Comment by bansp** [comment]
Let me try to handle this ASAP.

**Comment by bansp** [comment]
This is now implemented. Closing.
