### ISSUE TITLE
make sure that more than one maintainer can be listed for the centre

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#238]
This ticket has a schema side and a visualisation side.
We thought of providing a way to signal that a centre's recommendations are formally maintained by a person connected with a centre. But we should make sure that it is possible to split maintainership, and a great example is IDS, with its text part and a/v part of depositions, managed by separate departments. Also, if we extend into other research infrastructures, we've already seen examples where one institution is / has a CLARIN centre, a DARIAH repository, and also a Text+ centre, and it's not obvious that a single person wishes to be responsible for all.
A practical side to this is that the maintainer part of the schema should have an optional part for "comment" (not sure what to call the element/attribute) that would make the function of the given maintainer more precise. Maybe an attribute is enough, actually.

Assigning myself for the schema part and will switch to Eliza later for the visualisation part.

**Comment by bansp** [comment]
Reassigning to Eliza.

The `github` attribute should at some point probably be renamed to be more general, but, well, that's the environment we're in and that's where we expect PRs.

Added a `scope` attribute with free text. I didn't want to suggest anything but maybe I should have, given that it should be uniformly visualised. Let's just see how it works.

**Comment by bansp** [comment]
Eliza is going to add herself to IDS and see if it works (after she's implemented it :-))

**Comment by margaretha** [comment]
I have made it possible to add multiple curators. Please check the implementation in the dev branch. 

Should we change the element names as well? My suggestions:

- curator -> name
- github -> link
- function (new element)

**Comment by bansp** [comment]
After brainstorming, Eliza will commit the current source example (IDS recommendations), and Piotr will adjust the schema to that.

**Comment by margaretha** [comment]
Format:

Text format: [Piotr Banski](https://github.com/bansp) (July 24, 2023)

**Comment by bansp** [comment]
We're moving from 

```xml
<respStmt>
         <curator>Piotr Banski</curator>
         <github>https://github.com/bansp</github>
         <reviewDate>2023-07-24</reviewDate>
</respStmt>
```
to
```xml
      <respStmt>
         <name>Piotr Banski</name>
         <resp>text formats</resp>
         <link>https://github.com/bansp</link>
         <reviewDate>2023-07-24</reviewDate>
      </respStmt>
      <respStmt>
         <name>Eliza Margaretha Illig</name>
         <resp>audio visual formats</resp>
         <link>https://github.com/margaretha</link>
         <reviewDate>2023-12-19</reviewDate>
      </respStmt>
```
Please note that I've used Eliza's older suggestion of **link** rather than my probably not so good suggestion of **handle**.

**Comment by bansp** [comment]
I think I should perhaps add some more annotations, to assist centre representatives. Will see about that now.

**Comment by bansp** [comment]
We feel this should be closed, but Piotr wants to read through it to make sure.

**Comment by bansp** [comment]
Yep, sure now, closing.
