### ISSUE TITLE
Add domain info to centre and format pages

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#240]
For a centre, let us list the unique domains extracted from that centre's recommendations.

For a format, let us list all the unique domains that it appears with in all recommendations (globally). Note that this info can potentially be useful for sanity checking. Maybe the domains should have query functions attached to them, resolving to a list of centres that use the given domain in their recommendations?

**Comment by margaretha** [comment]
Eliza will add the domains in the format page as well.
