### ISSUE TITLE
additional names for a centre

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#245]
We've already seen issues where a centre is called one name in the CLARIN network, another in Text+, and has a third name for other purposes (or there exist minute organisational differences perhaps not fully relevant from the point of view of the SIS).

The listing of TALAR in re3data is a nice example of several issues, notably of handling the naming differences:
https://www.re3data.org/repository/r3d100010152
![image](https://github.com/clarin-eric/standards/assets/312137/a7e7e8b1-d684-48c6-9a94-e5962622da9a)

Let us make it possible to use more than one name for a centre / repository. Let these names get qualified by optional  attributes whose content is going to end up in brackets after the name. Hmm, or a loose attribute as above and a controlled `@ri` attribute, that could be used for the purpose of filtering...

One way or another, this is a schema + implementation ticket, so I am self-assigning it for the schema part and will switch to Eliza once I'm done.

**Comment by bansp** [comment]
Prioritising for myself; it's a short job and it would be good to handle it asaP.

**Comment by bansp** [comment]
This is what we have there right now, it must have been a rather quick patch:

```xml
               <xs:element name="centre" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element ref="a"/>
                            <xs:element ref="nodeInfo"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="deposition" type="xs:boolean" use="optional" default="false"/>
                    </xs:complexType>
                </xs:element>
```

I suggest to change "name" to "centreName", to make it more specific. I also suggest that `<a>` is misused here and should evolve.
Also, `centreName` should get the attributes `@ri` (restricted list) and a boolean `@preferred` that kicks in in the absence of `@ri`  (the logic should be a bit more complex here, actually -- processing `@ri`, checking for `@preferred` among identical values for `@ri`, and falling back on `@preferred` alone only if no `@ri`s are present -- right?).

**Comment by bansp** [comment]
Eliza says that `a` is probably not used at all.
Piotr will implement this for this milestone, but not before Eliza has a while to look at this ticket and comment.

**Comment by margaretha** [comment]
<a> is actually used to specify references to CLARIN centre pages. I agree we should change the element name. Maybe `<link>` like respStmt?

`@ri` attribute is rather ambiguous because we also have `<ri>` element in `<nodeInfo>`. Maybe `@restricted `? It is also more understandable than acronyms.

**Comment by bansp** [comment]
In the suggestion, `@ri` is meant to hold a restricted list of RIs, and was intentionally named the same as `<ri>`. I'll have to look at it again anyway, now, because it's not super-clear to myself anymore, either...

**Comment by bansp** [comment]
Just a remark for now: if we end up using `<link>` then something clever has to be done about the current annotation of `<link>`, which is RespStmt-specific. It is also not anyURI, which probably begs for a separate ticket...
We currently have three pointing elements in this schema: a, url, and link. Sigh.

**Comment by bansp** [comment]
Interim update (no, we're not done yet, it seems):
```xml
    <xs:element name="centre">
        <xs:complexType mixed="false">
            <xs:sequence>
                <xs:element name="name" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>the full name of the centre</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="registryLink" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="nodeInfo"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation xml:lang="en">'shorthand' for the centre that acts as its ID</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deposition" type="xs:boolean" use="optional" default="false"/>
        </xs:complexType>
    </xs:element>
```
So, `name`  is still not `centreName`, and it has no attributes.
I will not change that right now in formats, because I want formats to be instantly mergeable for Eliza tomorrow.

So we need to coordinate on this change, and maybe actually postpone it till post-CAC -- we should restrict ourselves to fixes and cosmetics, for the time being. BUT let me add Eliza to the assignees, and let me drop the priority label.

**Comment by bansp** [comment]
Meeting decision: keep it in this milestone and try to handle it before the release. Piotr will prioritize it for himself.

**Comment by bansp** [comment]
So this is now a quick task for Piotr. Breaking backwards compatibility for a week.

**Comment by bansp** [comment]
Again, recording the base state, before I act on this ticket:

```xml
<xs:element name="centre">
        <xs:annotation>
            <xs:documentation xml:lang="en">information about the centre</xs:documentation>
            <xs:appinfo>
                <sch:pattern xmlns:sch="http://purl.oclc.org/dsdl/schematron">
                    <sch:rule context="header/centre">
                        <sch:assert
                            test="count(../filter/centreID) = 0 or @id = ../filter/centreID/text()"
                            >The attribute @id of header/centre has to match header/filter/centreID if
                            the latter is present.</sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:sequence>
                <xs:element name="name" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>the full name of the centre</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="registryLink" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="nodeInfo"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation xml:lang="en">'shorthand' for the centre that acts as its ID</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deposition" type="xs:boolean" use="optional" default="false"/>
        </xs:complexType>
    </xs:element>
```

**Comment by bansp** [comment]
And this is my change, for the time being:
```xml
<xs:element name="centreName">
        <xs:annotation>
            <xs:documentation>the full name of the centre</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="ri" use="optional" type="ResearchInfrastructures">
                        <xs:annotation>
                            <xs:documentation>Name of the research infrastructure, if the preferred
                                centre name depends on the research
                                infrastructure.</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
```
-- this going to require only a minimal adjustment, and for the time being let's not force additional centre names on the centres that we list. Let's simply be prepared for such cases, so that we can implement centres' wishes in this regard, if such wishes are communicated to us.

Also, I decided to only implement the `@ri` attribute for now, not to complicate matters in advance.

**Comment by bansp** [comment]
Ah, I've gone ahead and fixed the implementation as well, so stuff is ready to upload (tested locally) and the ticket is ready to be closed.

**Comment by bansp** [comment]
Potential developments:

- adding actual name alternatives
- visualising name alternatives in centre info pages
- NOT grabbing all the names for the tables in list-centres and view-centre (so filtering after the RI and then [1])

-- but maybe let's cross that bridge only when we actually see the need to.
