### ISSUE TITLE
split centres.xml across the individual recommendations?

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#247]
I am not sure if we can find serious arguments against keeping the centre info separate from the recommendations.

Currently, **we list 51 centres and have 52 recommendation documents**, and that's already a yellow blinking light.

Each recommendation tells us something about the single centre, they are connected implicitly, via the file name. So, the info on the IDS in `centres.xml` is:
```xml
  <centre id="IDS" deposition="1">
    <name>Leibniz-Institut für Deutsche Sprache</name>
    <a href="https://centres.clarin.eu/centre/11"/>
    <nodeInfo>
      <ri status="B-centre">CLARIN</ri>
      <ri status="Collections, Lexical Resources, Operations">Text+</ri>
    </nodeInfo>
  </centre>
```

... and the filename of the recommendations is `IDS-recommendation.xml`. The recommendation file has a header, currently set to the following (and note the redundance between the file name and the `filter` element):
```xml
  <header>
      <lastUpdateCommitID>76e7d21871f644d0ea8b5b62811a493304d9cd18</lastUpdateCommitID>
      <filter>
         <centre>IDS</centre>
      </filter>
      
      <respStmt>
         <curator>Piotr Banski</curator>
         <github>https://github.com/bansp</github>
         <reviewDate>2023-07-24</reviewDate>
      </respStmt>
      
   </header>
```

(where the maintainer info was added for the sake of a demo at CAC-2023 and I don't consider it binding...)

Arguments for merging:

- data modelling: these pieces belong together, the relationship between the `centre` element and the relevant recommendation file should always be 1:1
- ease of maintenance: we'd only expect PRs of the recommendation files
- logic / data modelling: centres info is secondary to recommendations; it is not independent; we are not a centre-information facility -- that is the role of the CLARIN DB and the databases of other research infrastructures; we should only query those DBs in a sanity-checking operation, once in a while
- again a bit of a data-modelling issue: IF, say, centre X recommends one set of formats as a CLARIN/Text+ centre, and another as a DARIAH centre (and it's really a single institution, and that's how we want to represent it) then we can allow RI-specific attribute on `<formats>`: `<formats ri="dariah">` would be DARIAH-specific while `<formats>` would go for all the RIs involved. (this is not yet technically possible and won't be until we see the need for such an arrangement; but it would be good to have the base for that in place)
- centres list is a projection of recommendations; we don't use it separately for the (currently somewhat dormant) standards information part; it doesn't make sense to say that one centre does or does not use the given standard; the standards information should exist separately, and be information on standards, with maaaaybe a mention of some centre in the overall description. We don't need a skeletal list of centres, used by both format recommendations and standards info.

Argument against: technical complexity and bugs cropping up after the rearrangement, but that's a non-argument, really. It might be an argument for releasing 3.0.

**Comment by bansp** [comment]
To be sure: I suggest that each `<centre>` element goes into the header of a recommendations file, and that we get rid of `centres.xml`.

Being able to use the attribute `@ri` on `<formats>` is one thing that would follow. Another would be the use of that attribute on `<name>`, to differentiate between the centre name used for one RI vs. another (this is with reference to issue #245 ).

**Comment by margaretha** [comment]
Eliza will move centre elements to the recommendation files.

**Comment by bansp** [comment]
I will add the element as optional, for the time being, to the schema for recommendations. After the move, I'll make it obligatory.

**Comment by margaretha** [comment]
I mean in in export files when the format recommendations are not filtered by centreID, e.g.

```
<format id="fComa">
   <centre>HZSK</centre>
   <domain>Contextual Information</domain>
   <level>recommended</level>
</format>
```

**Comment by margaretha** [comment]
I have added centre elements in the recommendation files and updated the code to use them instead of the centres.xml. Please check the dev branch.

**Comment by margaretha** [comment]
> Currently, we list 51 centres and have 52 recommendation documents, and that's already a yellow blinking light.

This might happen when we change the id of a centre and forgot to remove its old recommendation file. 

Besides, it is also possible to have more centres than recommendation files when some centres have not created one or we haven't created a template for them. I think this case is okay, but we should be careful/take this into consideration when calculating KPI involving the number of centres.

**Comment by bansp** [comment]
Ah, I was wondering when I saw the duplicated info, both in `centres.xml` and in the individual recommendations. And it's been waiting for me! :-) 
Well, let it wait a while longer, since we have the issue open still so it won't be forgotten.
To be sure: the move looks fine to me, but I've only had a look rather than giving a try to a version with centres.xml either thinned down or altogether removed.
I'll get to that in mid-May, I expect.

**Comment by bansp** [comment]
It's mid-May so I am going to have a look now and most probably close it.

**Comment by bansp** [comment]
Don't want to close the ticket yet, because the info is still duplicated. I suggest that we remove centres.xml after the upcoming release and then deal with potential consequences. I'm moving this ticket to 2.8.0; it already has the priority label.
