### ISSUE TITLE
Make base URL dynamic

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#248]
Links in SIS are resolved with base-URL using the _app:link_ method. The base URL is set within app.xql, that is not dynamic, whereas the base URL differs between the production instance and localhost.

URL resolving is not necessary anymore, so the links can be relative now.

**Comment by margaretha** [comment]
Relative URL doesn't work for menu, so we still need URL resolving.

**Comment by bansp** [comment]
Just to make sure: should we change anything at the bottom of page https://github.com/clarin-eric/standards/wiki/Installation
(which discusses base URL modifications?)

**Comment by margaretha** [comment]
Yes, it is not needed anymore. Thanks for the reminder!
