### ISSUE TITLE
changed "centre" to "centreID" in the fields for filtered views/exports

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#249]
As part of handling issue #247 I needed to avoid an element clash, and realised that what we call "centre" in the schema for the "filter" element, is actually a centre ID. So I've changed the element name to "centreID", and the top of recommendation files now looks as follows:
```xml
<header>
      <lastUpdateCommitID>76e7d21871f644d0ea8b5b62811a493304d9cd18</lastUpdateCommitID>
      <filter>
         <centreID>IDS</centreID>
      </filter>
```
I'll change that in all the recommendation files in a moment, but I'd rather not touch the functionality layer for now (unless I will).
So I'm marking this as a task for @margaretha (again, unless I get to handle it myself), and adding the priority label for visibility.

**Comment by margaretha** [comment]
If we change <centre> to <centreID> in <filter>, I think we should also change <centre> within <format>

**Comment by bansp** [comment]
I thought I saw `<centre>` used within `<format>` and then I think I rationalised it by telling myself that I must have confused `<format>` with `<filter>`. I'm not sure why we would ever need `<centre>` inside `<format>`... Gonna check it out, thanks.

**Comment by bansp** [comment]
Can't see `<centre>` used within `<format>`. What did you have in mind, @margaretha , please?

**Comment by bansp** [comment]
I was completely confused for a moment, seeing this reply in an e-mail and not being able to locate it here.
Here's Eliza's reply from issue #247 
> I mean in in export files when the format recommendations are not filtered by centreID, e.g.
> 
> ```
> <format id="fComa">
>    <centre>HZSK</centre>
>    <domain>Contextual Information</domain>
>    <level>recommended</level>
> </format>
> ```

... and there's two things about this. Firstly, it's not in the schema! :-) I wonder if it ever was. Why don't I add it, with appropriate annotation, saying clearly that it's only for files exported from the "main view", so to say -- what do you think, @margaretha ?

The second thing is that it's a "centreID" as well, by the same token as the change under `<filter>`.
