### ISSUE TITLE
"Clarin Centre" heading a column in format information pages --> "Centre"

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#259]
I have a feeling that this may be a duplicate -- I'm rather sure we've been over this, at some point.

Open https://clarin.ids-mannheim.de/standards/views/view-format.xq?id=fGML

Under "recommendations", the first column has (badly capitalised) "Clarin" over it, while it shouldn't , if we want to be RI-interoperable :-)

**Comment by margaretha** [comment]
Thanks for pointing it out. I forgot to update the it in the format pages when I updated it in the recommendation page.

**Comment by bansp** [comment]
Ah, hence my déjà vu :-)
Thanks a lot, @margaretha , for the quick action! Closing -- I can see the result in the live instance.
