### ISSUE TITLE
Pilot adding the data from CLARIN-EL

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#260]
**Centre concerned**
CLARIN-EL

https://clarin.ids-mannheim.de/standards/views/view-centre.xq?id=CLARIN-EL

- Work with the centre, possibly via @maria-gav (Maria), to smoothen the path for them in adding their format recommendations into the SIS
- See if any clues from the centres that have been through an "inputhon" (IDS, FIN-CLARIN) can be gathered to extend the existing documentation (ask @mmatthiesencsc )
- Use this as an opportunity to potentially update the existing docs (I've just updated the [syntax overview](https://github.com/clarin-eric/standards/wiki/Detailed-syntax-of-information-elements-in-the-SIS))

Maria wrote (a while ago already -- apologies for the delay in reacting!)

> (..) 
> - the link to the file with all the accepted & recommended formats is this https://www.clarin.gr/sites/default/files/CLARINELRecommendedFormats.pdf
> - which can be found here https://www.clarin.gr/en/services/share, together with the Data Collection Policy and Preservation Policy documents. We plan to change their position in the portal, so that they can be more easily found, but for the time being this is their location.

**Comment by bansp** [comment]
(Recording the issue -- I'll be able to assist since around mid-May.)

**Comment by mmatthiesencsc** [comment]
We can have a chat about our experiences, if that helps. I had a quick look through https://www.clarin.gr/sites/default/files/CLARINELRecommendedFormats.pdf and would recommend to trim down the recommended formats even further. We did this with the understanding, that a not mentioned format does not automatically mean we won't take it, but it means we prefer some over others.

**Comment by bansp** [comment]
It looks like this is not happening for the current bunch of recommendations, so I'm moving the ticket to the next milestone, for housekeeping reasons.

**Comment by bansp** [comment]
Since monitoring of the centres' activity wrt the SIS has been adopted by the Centres Committee as a cyclic task, there appears to be no need to put the spotlight on CLARIN:EL as opposed to other centres/consortia. I suggest that we close this ticket as unresolved.

**Comment by maria-gav** [comment]
No objection on out part.
Best,
Maria

Maria Gavriilidou
ILSP / RC ATHENA
Artemidos 6
15125 Marousi
Tel. 210 6875441
www.ilsp.gr<http://www.ilsp.gr> www.athenarc.gr<http://www.athenarc.gr>

**Comment by bansp** [comment]
Closing, as agreed above.
