### ISSUE TITLE
list of keywords, maybe under sanity check

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#269]
It would be good to be able to access an alphabetized list of keywords, maybe under the sanity check page: so that we can spot typos, lonely keywords, etc.

I imagine something like:

- ...
- container format (4)
- ...

(where "4" is the number of f*.xml files from under data/formats/ that use the key phrase "container format")

Since we are late in the release process, I'm categorising this as 2.8.0. It would be super helpful to have this for a review of file format information docs... :-)

**Comment by bansp** [comment]
Ideally:


- ...
- container format (4)
   - name1, linked to the doc
   - name2, linked to the doc 
   - ...
   - ...
- ...

-- in order to be able to do some quick across-the-board key phrase adjustment.

**Comment by bansp** [comment]
This is almost done, bar some minor glitch that requires authentication before accessing this page.
@margaretha  has been notified.

**Comment by margaretha** [comment]
Sorry about that. Fixed in 2fd6e2d9b3e66b6948b5599452ee15367a371e5c
