### ISSUE TITLE
KPI page: enhancement needed

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#273]
1. It seems to me that we need a date stamp for the KPI calculation. 
2. We also need to make this calculation easy to verify, so the phrase "depositing centres" needs to link to the list of exactly those centres that we use for calculation.
3. The last paragraph has become gibberish. It needs to be fixed ASAP, before release 2.7.0.

**Comment by bansp** [comment]
Regarding point (3) above,
```
The SIS provides information on all <a href="{app:link("views/list-centres.xq")}">centres that allow
                                    for data depositions</a>
```
lacks the appropriate filter for centres that allow data deposition.
(Apart from that, the "all" is a bit bold and needs to be even further qualified. "All CLARIN" seems the easiest to do.)

**Comment by bansp** [comment]
4. This is wrong, isn't it:
```html
<td class="column">CLARIN deposition centres recorded in the SIS</td>
<td class="column">{$numOfBCentres}</td>
```

We've been through this for the paper (when recalculating the KPI at the time of submission), but we may have forgotten (?) to modify the KPI page as well.

**Comment by bansp** [comment]
I have handled point 3., and point 4. was just a misnamed variable, fixed on the way to release 2.7.0.

**Comment by margaretha** [comment]
Eliza should check if there is a replacement of semicolon etc to underscore, probably in export.

**Comment by margaretha** [comment]
We can add current timestamp for the KPI calculation.

**Comment by margaretha** [comment]
I have added a date stamp addressing point 1. 

To which page should "depositing centres" link? Centre or Centre Statistics page?

**Comment by bansp** [comment]
Meeting decision: the KPI page should link to the centre statistics page, and that other page should get a new column, for those centres that have provided information.
