### ISSUE TITLE
Add info file for the Menota format

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#275]
Inspired by #271 : 

**ID**: fMenota or  fMenTEI or ...
**Long name**: Medieval Nordic encoding format (?)
**Abbreviation**: Menota or ... (?)

@OyvindLGjesdal : would you like to suggest anything specific for the fields above, please? (see  https://standards.clarin.eu/sis/views/list-formats.xq for some examples)

**Description**: a quote from https://menota.org/HB3_ch1.xml may be enough, mention https://menota.org/HB3_D_schemas.xml 

**File ext**: .xml
**Media type**: application/xml+tei
**Family**: TEI

**Comment by bansp** [comment]
Online at https://standards.clarin.eu/sis/views/view-format.xq?id=fMenota , closing the issue.

**Comment by OyvindLGjesdal** [comment]
Thanks for following up
