### ISSUE TITLE
some centres apparently didn't get anything copied over from centres.xml

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#287]
Found ACE and ASV so far, the latter with a wrong ID set.

**Comment by bansp** [comment]
@margaretha you might want to know about these, maybe it's something systemic that cropped up when copying info from centres.xml to the individual recommendations. (And I overlooked that, too.)

**Comment by bansp** [comment]
Wooot, these two do not show up in the SIS centre listing at all.
ACE is a K-centre, ASV isn't even listed by the CLARIN registry. Something is wrong... I'm removing them.

**Comment by bansp** [comment]
I think I may be looking a K-centres recovered from your backup, @margaretha , after I'd removed them. Is that a plausible story? Can't recall now, but I think I did that after the SIC had suggested that.

**Comment by bansp** [comment]
Ready to close, I think. There are some non-depositing C-centres remaining on the list, but they are useful checks.

**Comment by margaretha** [comment]
The files in the database have be manually deleted, because we use "Store files" that only add new files and edit existing files.  Sorry that I have overseen the centres that should have been deleted. Thanks for the fix!
