### ISSUE TITLE
too little retrieved via the API if filters added

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#295]
At the API page, we suggest, e.g.:

`curl 'https://clarin.ids-mannheim.de/standards/rest/views/recommended-formats-with-search.xq?centre=IDS&domain=1&level=recommended&ri=Text%2B&export=yes'`

but the result is, a.o., the following:

```xml
   <formats>
        <format id="fMPEG-4-AVC">
            <comment>25 fps, 1920×1080, constant bit rate </comment>
        </format>
        <format id="fWave">
            <comment>PCM-WAV, 48 kHz, 16 bit</comment>
        </format>
    </formats>
```

If the filters (domain, level) are omitted, the returned data is OK.

**Comment by margaretha** [comment]
Hi Piotr,
thanks for the remark. As far as I see, the results are as expected. I suppose we agreed to omit what have been already written in the the filter to avoid redundancy, because it will be the same for all format entry.

```

<filter>
<centreID>IDS</centreID>
<domain>Audiovisual Source Language Data</domain>
<level>recommended</level>
</filter>
```

**Comment by bansp** [comment]
I am not sure if that was the right idea. Let's discuss it at some point. 
Apologies for the 'bug' label! And thanks for reminding me of the story :-)

**Comment by bansp** [comment]
Meeting conclusion: we can imagine various use cases for this and are going to close this issue as a wontfix.
We're ready to reopen if there is a need for that (but we need a signal).
