### ISSUE TITLE
collapsible sections (again)

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#303]
We used to have a "collapse/expand" functionality in the list of functional domains once. 

It came back to me as I look at the list of domains that we print in `view-centre`. I _do_ think that the list is useful, but I also think that it's a bit secondary (being, after all, fully redundant wrt the recommendations) and it might be a good idea to display it as collapsed initially, and the expandable upon a click after the section title.

I think there are more sections in the info we display that would benefit from that. Pieces of the sanity checker come to mind.

So this is an idea for such general functionality (probably not a new module? it feels like a piece of js+css job) that we could just use whenever we feel like delegating the choice of seeing some info to the user.

**Comment by margaretha** [comment]
Eliza can add ... after the label for the collapse function when it is collapsed and it should be hidden when it is expandedn.

**Comment by bansp** [comment]
Test cases:
 
(e.g.) https://standards.clarin.eu/sis/views/view-centre.xq?id=BBAW  (in the collapsed state, there could be a '...', which, upon expansion, is replaced with a newline and the relevant list (and probably the header of that list).

vs. pages under the "Sanity check" menu on the left, where the "..." wouldn't fit.

**Comment by bansp** [comment]
It looks great, we can close the issue. :-)
