### ISSUE TITLE
favicon for the browser tab?

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#310]
I can't recall for sure: didn't we have a favicon for the SIS? Maybe it's just a question of adapting it to some newer browser demands.

This is partially a note for myself, to check with the Office if they have a set of "corporate" favicons that we could pick from. 

It would simply feel better / be nicer / more professional if the tab with the SIS carried some graphic rather than the default emptiness.

**Comment by margaretha** [comment]
The favicon is used to show IDS logo at SIS tab. We agree to change it to CLARIN logo. Piotr will ask for the CLARIN logo and Eliza will check the code and do the replacement.

**Comment by bansp** [comment]
I have (indirectly, via Thalassia) contacted the CLARIN communications team, but should probably expect their reaction only on Monday. One way or another, there is a chance for us to have the favicon before the upcoming CAC.

**Comment by bansp** [comment]
Update:

**Comment by margaretha** [comment]
Eliza will setup the new favicon.
