### ISSUE TITLE
(X)HTML vs HTML 5

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#323]
I wonder about this declaration, that is present in many or all the `views/` files.

```xquery
declare option exist:serialize "method=xhtml media-type=text/html indent=yes doctype-system=about:legacy-compat";
```

What the given doc proceeds to output is the root `<html>` element -- which I've recently changed by adding a `@lang` attribute, but which, one way or another, is an HTML 5 root element, because, for one thing, it lacks a namespace declaration.

SO, if I'm not mistaken, we are declaring HTML 4 (indeed XML) syntax but produce HTML 5 documents. Is that correct?

**Comment by margaretha** [comment]
Thanks for the remarks. The method `option` is actually outdated and should be considered as deprecated according to the eXist-db documentation https://exist-db.org/exist/apps/doc/xquery

We should change it to the standard XQuery serialization parameters (see https://www.w3.org/TR/xslt-xquery-serialization-31/#serparam). There is an option for `html` which is more appropriate than `xhtml`, and we can also specify the `html-version`, which automatically generates `<!DOCTYPE html>`.

So the exist serialization declaration should be replaced with:

```
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method "html";
declare option output:media-type "text/html";
declare option output:indent "yes";
declare option output:html-version "5";
```

**Comment by bansp** [comment]
Thanks a lot for investigating that! :-)
