### ISSUE TITLE
exports don't validate

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#326]
When I export all recommendations:

1. the entire file is stamped with a `<!DOCTYPE recommendation SYSTEM "about:legacy-compat">` (that is not necessary at all, and it seems a new development)
2. the file doesn't validate, because it lacks the `<info>` element (and for a good reason, in this case)

Additionally,

3. if "all RIs" is chosen before the export, the export contains ` <ri>all</ri>`, which doesn't validate (and maybe again that's OK)

The 2nd issue is probably an artefact of our decision to merge centre listing with the recommendations.

I can see several ways out of this (apart from the obvious one, to drop the DOCTYPE):  

1. modify the schema to make `<info>` optional, so that the exported recommendations can validate, 
2. have a new, different schema for the export
4. take the schema out altogether (the structure is totally regular, and no one is going to extend or modify this file, it's just yet another way to time-stamp a project snapshot)

I think that, for now, I am going to take the 3rd option, for the purpose of recommendations release.
But let's think about it, making `<info>` optional is also a possibility. I am not sure that I would like to add "all" to the list of RIs, though.

For now, the suggested task list is:

- drop the DOCTYPE
- drop the schema

**Comment by bansp** [comment]
Eliza has addressed this in commit [72c2bcf](https://github.com/clarin-eric/standards/commit/72c2bcfdb312b3bece076b2ece662eb5a7046e79)

**Comment by bansp** [comment]
We have another solution: create the `<info>` element for "all recommendations", upon export. This way, the schema is going to be satisfied, and we will provide some basic information.

**Comment by bansp** [comment]
(and we see some new thing: it's like `info` in the export of individual centres is getting changed to `span`. We need to investigate that :-) )

**Comment by margaretha** [comment]
Fixed the DOCTYPE in 72c2bcfdb312b3bece076b2ece662eb5a7046e79 and span issue in f11eb37c1983ffaff39cd0e73cc141bc22643b71
