### ISSUE TITLE
Have a way for centres to explain deprecation

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#33]
It's just struck me that, upon seeing something like 

```xml
<format>
   <name id="fCHAT">CHAT</name>
   <domain>Audiovisual Annotation</domain>
   <level>deprecated</level>
</format>
```
(rendered appropriately), some may wonder, and some may feel annoyed.

It might be good to have a way for a centre to point the user either to an explanation, or to an alternative (in the case at hand, simply a more expressive format).

I wonder if it's a matter of a pointer attribute on `<level>`, or whether we should also allow for a more verbose in-situ option. Hmm, that can still be a (text-holding) attribute. Maybe its being an attribute would encourage short explanations. Like:

```xml
   <level target="fISOTEI" tip="more expressive format preferred">deprecated</level>
```

Would that work?

(Aside: I have skipped domain ID here, because it seems to me that, given how much stress we've put into making this a basis for a human-based workflow and into ensuring that it's easy to copy the domain name without errors, maybe we should drop the IDs for domains and use text matching. This is of course going to become a subject of another ticket, but I need to store the thought somewhere at least temporarily.)

**Comment by hannahedeland** [comment]
Some thoughts on that:

Maybe we should just try changing from "deprecated" to "not recommended", since deprecation is maybe not the right expression here anyway, talking about formats created and potentially used by others.

And maybe we should rather aim for a general information section on reasons for not recommending a format, which could be, apart from problems with the format itself, e.g. internal workflows and/or a centre's specific quality requirements. Asking centres to point out the problems with formats used elsewhere might become a bit difficult.

And since there might be several formats within the same functional domain that are all recommended to the same extent by a certain centre, we should both already have this information in the SIS (hopefully) and it might not be that easily integrated into an attribute. For more detailed information on which formats to use when, it's probably better to just contact the centre.

**Comment by bansp** [comment]
I do prefer to keep it simple, and it might be that what's meant as a little piece of explanation for deprecation would overgrow the original intent. So I'll be happy to drop the suggestion.
The three values are already a compromise, because sometimes you do talk of active deprecation or discouragement (think "Phon1" at BAS), and sometimes something is just, as you say, "not recommended", for various reasons. Let's bring this point up in the next meeting, perhaps? I'm also a bit worried here, given the open-world perspective that we must adopt for the interpretation of these recommendations, that "not recommended" may create the wrong entailments (but maybe I'm overthinking it).

**Comment by hannahedeland** [comment]
I guess ideally we'd have both "deprecated" with a reference to the successor, used by centres about formats they are responsible for and/or where there is a clear versioning, and "not recommended" for the recommendations to potential depositors at specific centres. In some cases, "not accepted" would be more appropriate, but sometimes centres will want to state that formats are not recommended though they will still accept valuable data in these formats... So yes, let's discuss this again :)

**Comment by bansp** [comment]
There is also another kind of "deprecation" that may bite us, namely CLARIN-wide deprecation of unqualified "XML" or unqualified "TEI", etc. Maybe this is something that we should protect the SIS from, by not allowing anything like "fXML" or "fTEI" in the recommendations (though we might want to allow for them in the list of formats, to state in their description that they are "heads of families", while we're only interested in the well-defined members of those families, if we want to be informative rather than blatant.

**Comment by bansp** [comment]
I am afraid that, if no opportunity to comment and point is provided by us, many centres are going to shun this system, because in their own pages they do provide comments and often also point.

**Comment by bansp** [comment]
Aside from the overall handling of the term "deprecation" or its equivalent(s), it is now possible to attach comments to individual recommendations, as per issue #39 .

**Comment by TomazErjavec** [comment]
Coming a bit late to this, but I agree with @hannahedeland that "deprecated" is not the right term in most cases, as it implies that that the format was ok some time ago (for the centre) but it is no longer so. I would advocate the simple and unambiguous "not accepted", I think it says exactly what is meant - we don't wan't this format. And it doesn't really matter if it was ok 5 years ago.

As for "sometimes centres will want to state that formats are not recommended though they will still accept valuable data in these formats" I think this is then up to the provider / centre to decide to accept it, even though they say they don't - I would think that for valuble data it would be converted to something better in any case, but if not, "every rule has an exception".

**Comment by bansp** [comment]
So, at this point, `@tip` is already discarded as an idea.
Next, 

- "deprecated" has, arguably, wrong connotations
- "not accepted" is still strong, I can imagine centres not wanting to formulate it so strongly because not everyone is prepared to seek systemic exceptions to rules
- "discouraged" is the path we haven't explored yet, it seems; doesn't it cover the other cases quite satisfactorily, or am I caught in the web of my private interpretations of the meanings of words?

**Comment by TomazErjavec** [comment]
I like "discouraged".

**Comment by bansp** [comment]
I have put it on the agenda of today's SIC meeting.

**Comment by bansp** [comment]
Green light from the committee for the change. 
I think I'd rather put it off till tomorrow afternoon ("don't fix a working system just one day before you demo it").

**Comment by bansp** [comment]
> I guess ideally we'd have both "deprecated" with a reference to the successor, used by centres about formats they are responsible for and/or where there is a clear versioning, and "not recommended" for the recommendations to potential depositors at specific centres.

This is exactly what is left. There is a way to deprecate something system-wide (vide the Phon formats), and "deprecated" as a value of a centre's recommendation has now become "discouraged".
