### ISSUE TITLE
Adding commit id to the web

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#36]
It is beneficial to be able to tell exactly which version of SIS is running, e.g. on the production server, so that any problem and bug reports can be identified effectively. 

One solution to do so is to use a git hook to automatically write down the latest commit-id, ideally when pulling from master.  The system should read from this file and present the commit-id somewhere in the website, e.g. contact page.

**Comment by margaretha** [comment]
@bansp I have written a simple[ post-merge git hook](https://git-scm.com/docs/githooks#_post_merge) that automatically writes down the latest commit-id. However, the hook is invoked by `merge` instead of `pull` so there is a possibility that commit-id is not updated when there is no `merge` within a pull request.

Besides, the post-merge hook would possibly not help much in the development or showing incorrect commit-id, unless we do a merge from another branch.

**Comment by bansp** [comment]
Gosh, I got lost when reading up on what one can hook to.
I wonder: would it make sense to create the commit-id on more than one hook? In the sense that it might sometimes get overwritten several times in one cycle of 'action', but, eventually, it increases the chance of the ID to be (1)  captured and (2) current. 
Also, there are several push-related hooks. Would that perhaps be a way out, in the sense that whether you merge or rebase, you push stuff to github, in the end? Or does something crucial escape me in this picture, please?

**Comment by margaretha** [comment]
The commit id should be shown in footer and also included in links to  GH issue templates.
