### ISSUE TITLE
Simplify the input further: eliminate the format/name element in favour of format/@id

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#41]
Currently, we do
`<name id="fPDFA">PDF/A</name>`
in the individual recommendation files. Let me note the question that Eliza asked once, when we simplified the domains: why not get rid of either the format ID (like we did with domain ID) or the format name?
It seems to me, now that we have a lot of recommendations encoded manually, that sticking to the format ID may be safer, because I've seen more than one expansion of the "short name" of a format (some are simply not institutionalized in any way).
So I would suggest to go for something like:
`<name id="fPDFA"/>`, to yield something like:
```xml
        <format>
            <name id="fPDFA"/>
            <domain>Textual Source Language Data</domain>
            <level>recommended</level>
        </format>
```
Dang... what about:

```xml
        <format id="fPDFA">
            <domain>Textual Source Language Data</domain>
            <level>recommended</level>
        </format>
```

?

**Comment by bansp** [comment]
By e-mail, Eliza agrees that the latter suggestion is a good target.

**Comment by margaretha** [comment]
> We need to leave `<name>` as optional, though, for formats that have no representation as files. So the logic for printing the name in the relevant column should be:
> 
>     * find the format file by ID
>       
>       * if failure, retrieve the name from `<name>`
>         
>         * if failure, use the ID (so that we can catch the issue while falling back)
>       * otherwise retrieve the name from `<abbr>` within the format description file
> 
> 
> But let's do all the statistics (in the future) based on the format IDs, rather than format names.

Hi Piotr, thanks for the issue. Is this comment still relevant?

I have updated the format id as attributes and simply removed the name element in baa431ce5ae1bfc7f051d793429f7a8ff4048cb6.

I believe we agree to just include the format ID in the recommendation table when no corresponding format description file is found.

**Comment by bansp** [comment]
Yes, we talked after I wrote and commented on the ticket, and I should have updated the ticket after we talked, sorry.
Thanks for the changes, @margaretha , will check them out!

**Comment by bansp** [comment]
A note from our meeting: for the sake of appearances, we will remove the leading "f" from IDs and sort the remaining strings among the existing format names.
