### ISSUE TITLE
pre-code domains in the import

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#42]
This is another idea for simplification or maybe user-friendliness rather than simplification per se.

My use case is a centre representative who wants to encode their recommendations, and opens a blank input file for their centre (because, let's say, the centre has freshly obtained the B status or has not published recommendations before).

The task of that representative may be a bit overwhelming if they have to look up domain names, copy them and encode.
What if they were to see, minimally, a sequence such as:

```xml
        <format id="null">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="null">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="null">
            <domain>Catalogue Metadata</domain>
            <level>recommended</level>
        </format>
      ...
```
(I assumed in the above that the innovation suggested in issue #41 is accepted)

"null" formats would be disregarded for the purpose of listing/statistics. But the presence of pre-filled templates that one could copy and fill in could be very helpful in reducing the panic factor and increasing accuracy of the result.

**Comment by margaretha** [comment]
I will add these in the recommendation files, but they will no be included in an exported file.

**Comment by bansp** [comment]
I am not entirely sure that this pre-coding is needed, given that the schema now offers content substitution and screams about wrong domain names, and also provides glosses for domain names, when the recommendations are edited in a suitable XML editor.

**Comment by bansp** [comment]
Piotr will provide some basic hints within those comments.
And we only want to start with a single domain, commented, as a template.

**Comment by bansp** [comment]
I was supposed to add a comment to those templates, but I can't see what they are generated by, @margaretha can you please point me there? :-) Tried to browse the commits starting from the one above, but failed to find that spot. 
They weren't added by hand, or were they?

**Comment by bansp** [comment]
If this is anything that can be done within the code, I'll do that tomorrow morning in the formats branch, then sync that with the master and release. And then we'll take care of the changes that are currently in the dev, OK, @margaretha ?

**Comment by margaretha** [comment]
I actually made a script to do this task and as we have discussed in our meeting, I should include the functionality to the sort-format.xq.

**Comment by bansp** [comment]
Thanks @margaretha , have you pushed that, by any chance? Nothing's coming my way when I pull from dev.

**Comment by bansp** [comment]
@bansp please continue now that the script is committed
