### ISSUE TITLE
parse format references inside `<comment>` and `<info>` elements

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#59]
This is to record the idea, without a specific commitment at this point.
It might be good to be able to parse references such as " #fGIF " in the comments to turn them into `<a>`s.
A use case is where a centre says, for example, that "we deprecate this format because we can't handle it easily, so please use #fOtherFormat instead", and the `#fOtherFormat` is turned into `...views/view-format.xq?id=fOtherFormat` . 

I've already seen a lot of places where that would come in handy, when encoding e.g. the recommendations by DANS.

**Comment by bansp** [comment]
The `<info>` element is the general description of a centre, to be (hopefully) moved from centres.xml into the particular recomendations (issue #196 ).

**Comment by bansp** [comment]
Promoting to 2.5.0 hoping for Eliza's OK (it's part of the hub inputhon ticket).

**Comment by bansp** [comment]
This needs some thinking in quiet, because it's not substitution of text by text, but rather splitting a text node with an element (`<a>`), and while it feels that the solution should be there, we still need to weigh all the potential consequences. So we will most probably postpone this to the next milestone.

**Comment by margaretha** [comment]
It would be much easier if the substitution is not carried out at text level but node/element level. Would it be fine if the references are written as XML elements, e.g. `<format>fAGS</format>` or `<format @id="fAGS"/>` ?

In this case, we can do _update replace node_ as follows:
```
for $format in $info/p/format
  return update replace $format with <a href="{app:link(concat(
  "views/view-format.xq?id=",$format/text()))}">{$format/text()}</a>
```
This code will actually update the file content as well.

**Comment by bansp** [comment]
Thanks for giving it a thought, Eliza! :-) I think we can easily have this, the short version is nearly no different than the ID itself. 

It probably doesn't make sense for me to restrict the values to the existing (=described) formats, does it. But maybe I could issue a warning if the ID is outside the existing set.

**Comment by bansp** [comment]
The only thing left now is to legalize this with a schema, and @bansp is going to do that. Otherwise this ticket is ready to be closed.
