### ISSUE TITLE
Shorten the commit ID for convenience

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#99]
This is a follow-up to issue #36 that Eliza and I discussed earlier today in a meeting and I'm recording it just for our convenience (and also for when we're assessed on the basis of our involvement in the work here ;-)).

It's a minor enhancement: in the footer, we'll have the label "Version ID:" followed by the reduced (6-digit) commit ID, with a full link to the commit (as it is now). I will then be able to use the shortened version for the titles of issue templates.

**Comment by margaretha** [comment]
Implemented in cfe9a8c0f58f3fe9eee19bbfd6d6991ccb114f5c
